In [26]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [27]:
x1 = pd.read_csv("t1_1.csv")
y1 = pd.read_csv("t10_1.csv")
x2 = pd.read_csv("t11_1.csv")
y2 = pd.read_csv("t12_1.csv")
x3 = pd.read_csv("t10_2.csv")
y3 = pd.read_csv("t1_2.csv")
x4 = pd.read_csv("t12_2.csv")
y4 = pd.read_csv("t11_2.csv")

In [28]:
# x1 -> y1, y2, y4

df1 = pd.DataFrame()
df1 = pd.concat([y1, y2], axis=1)
df1 = pd.concat([df1, y4], axis=1)

In [29]:
X_1 = x1[['교통량']]
y_1 = df1[['교통량']]

In [30]:
model1 = LinearRegression()
model1.fit(X_1, y_1)
y_predict1 = model1.predict(X_1)

In [31]:
print(model1.intercept_)
print(model1.coef_)

[ -6.83429156 -23.56641728 -15.1183534 ]
[[0.98022624]
 [0.74164842]
 [0.64819649]]


In [32]:
# x2 -> y1, y2, y3

df2 = pd.DataFrame()
df2 = pd.concat([y1, y2], axis=1)
df2 = pd.concat([df2, y3], axis=1)

In [33]:
X_2 = x2[['교통량']]
y_2 = df2[['교통량']]

In [34]:
model2 = LinearRegression()
model2.fit(X_2, y_2)
y_predict2 = model2.predict(X_2)

In [35]:
print(model2.intercept_)
print(model2.coef_)

[48.56495109 -5.29061871 40.3542097 ]
[[1.43913531]
 [1.19237395]
 [1.63459064]]


In [36]:
# x3 -> y2, y3, y4

df3 = pd.DataFrame()
df3 = pd.concat([y2, y3], axis=1)
df3 = pd.concat([df3, y4], axis=1)

In [37]:
X_3 = x3[['교통량']]
y_3 = df3[['교통량']]

In [38]:
model3 = LinearRegression()
model3.fit(X_3, y_3)
y_predict3 = model3.predict(X_3)

In [39]:
print(model3.intercept_)
print(model3.coef_)

[-2.26672735  6.80616826  5.70455071]
[[0.65138532]
 [0.98414135]
 [0.56396833]]


In [40]:
# x4 -> y1, y3, y4

df4 = pd.DataFrame()
df4 = pd.concat([y1, y3], axis=1)
df4 = pd.concat([df4, y4], axis=1)

In [41]:
X_4 = x4[['교통량']]
y_4 = df4[['교통량']]

In [42]:
model4 = LinearRegression()
model4.fit(X_4, y_4)
y_predict4 = model4.predict(X_4)

In [43]:
print(model4.intercept_)
print(model4.coef_)

[60.53467082 61.12700149  2.90917467]
[[1.14599797]
 [1.27566917]
 [0.85378695]]
