In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x1 = pd.read_csv("t1_1.csv")
y1 = pd.read_csv("t10_1.csv")
x2 = pd.read_csv("t11_1.csv")
y2 = pd.read_csv("t12_1.csv")
x3 = pd.read_csv("t10_2.csv")
y3 = pd.read_csv("t1_2.csv")
x4 = pd.read_csv("t12_2.csv")
y4 = pd.read_csv("t11_2.csv")

In [4]:
# x1, x2, x4 -> y1

df1 = pd.DataFrame()
df1 = pd.concat([x1, x2], axis=1)
df1 = pd.concat([df1, x4], axis=1)

In [5]:
X_1 = df1[['교통량']]
y_1 = y1[['교통량']]

In [7]:
model1 = LinearRegression()
model1.fit(X_1, y_1)
y_predict1 = model1.predict(X_1)

In [10]:
print(model1.intercept_)
print(model1.coef_)

[-7.02779083]
[[ 0.95959409 -0.08318616  0.09869829]]


In [12]:
# x1 ,x2, x3 -> y2

df2 = pd.DataFrame()
df2 = pd.concat([x1, x2], axis=1)
df2 = pd.concat([df2, x3], axis=1)

In [13]:
X_2 = df2[['교통량']]
y_2 = y2[['교통량']]

In [18]:
model2 = LinearRegression()
model2.fit(X_2, y_2)
y_predict2 = model2.predict(X_2)

In [19]:
print(model2.intercept_)
print(model2.coef_)

[-3.82377065]
[[-0.04256747  1.21157353  0.02618937]]


In [20]:
# x2, x3, x4 -> y3

df3 = pd.DataFrame()
df3 = pd.concat([x2, x3], axis=1)
df3 = pd.concat([df3, x4], axis=1)

In [21]:
X_3 = df3[['교통량']]
y_3 = y3[['교통량']]

In [22]:
model3 = LinearRegression()
model3.fit(X_3, y_3)
y_predict3 = model3.predict(X_3)

In [23]:
print(model3.intercept_)
print(model3.coef_)

[5.76814521]
[[0.00457993 0.93971664 0.06642866]]


In [24]:
# x1, x3, x4 -> y4

df4 = pd.DataFrame()
df4 = pd.concat([x1, x3], axis=1)
df4 = pd.concat([df4, x4], axis=1)

In [25]:
X_4 = df4[['교통량']]
y_4 = y4[['교통량']]

In [26]:
model4 = LinearRegression()
model4.fit(X_4, y_4)
y_predict4 = model4.predict(X_4)

In [27]:
print(model4.intercept_)
print(model4.coef_)

[-7.36914033]
[[0.05661243 0.10563992 0.65268117]]
